# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.applyDefaultHierarchyTemplate=false

# Enable R8 full mode for better compression
android.enableR8.fullMode=true
# Optimize resources
android.enableResourceOptimizations=true
