# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Point to a full JDK that has jpackage (Required for .deb packaging)
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk

kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
